#!/usr/bin/env python3
"""Resolve AGENTS.md hierarchy and doc workspace state for goal runs."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


DEFAULT_GLOBAL_AGENTS = Path(
    os.environ.get("CODEX_GLOBAL_AGENTS", str(Path.home() / ".codex" / "AGENTS.md"))
)
PROCESS_DOCS = [
    "task_plan.md",
    "progress.md",
    "findings.md",
    "task_issue.md",
    "lessons.md",
]
SKILL_NAME = "goal-context"
LEGACY_SKILL_NAMES = ("harness-agents-md-context", "harness-agent-for-goal")
GENERATED_MARKER = f"<!-- {SKILL_NAME}:generated -->"
BOOT_MARKER_PREFIX = f"<!-- {SKILL_NAME}:boot:"
PATH_INDEX_BEGIN = f"<!-- {SKILL_NAME}:path-index:start -->"
PATH_INDEX_END = f"<!-- {SKILL_NAME}:path-index:end -->"
LEGACY_PATH_INDEX_MARKERS = [
    (f"<!-- {legacy}:path-index:start -->", f"<!-- {legacy}:path-index:end -->")
    for legacy in LEGACY_SKILL_NAMES
]
EXCLUDED_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "__pycache__",
    "node_modules",
    "dist",
    "build",
    "target",
    "venv",
}
MANIFEST_NAMES = {
    "Makefile",
    "package.json",
    "pyproject.toml",
    "requirements.txt",
    "setup.cfg",
    "setup.py",
    "tox.ini",
    "uv.lock",
}
CODE_SUFFIXES = {
    ".py",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".go",
    ".rs",
    ".java",
    ".sh",
    ".yaml",
    ".yml",
}
SENSITIVE_SUFFIXES = {".env", ".key", ".pem", ".p12", ".crt"}


GLOBAL_TEMPLATE = """# Global AGENTS.md

These rules apply before project-specific AGENTS.md files. User instructions
in the current chat still have highest priority.

## Core Rules

- Start from the user's motivation and choose the shortest necessary path that
  can meet the goal without creating avoidable frontend, backend, or workflow
  risk.
- If the user's need is unclear, ask before changing code. If it is clear,
  execute directly and keep status updates short.
- For non-trivial work, route through goal-entry first. Main thread
  keeps synthesis and final authority; subagents do task details and report
  concise conclusions.
- Do not show raw tool JSON, raw subagent notifications, or internal process
  dumps to the user. Translate them into two or three natural sentences unless
  the user explicitly asks for raw output.
- Stop immediately on logical contradiction, unsafe environment state, or
  permission risk. Do not compensate with downgrade patches or after-the-fact
  fixes that hide the problem.

## Authorization And Isolation

- Subagents must not create branches, create worktrees, merge work, call Codex
  goal tools, or edit outside their assigned write scope.
- Architecture changes, non-target edits, destructive operations, and new
  worktrees require explicit main-orchestrator authorization; if user approval
  is required, wait for a clear "Yes".
- Keep modules physically decoupled. Do not pass hidden global state between
  agents or rely on implicit environment variables for task data.

## Code Discipline

- Prefer a stable model, table, parser, or existing system function over a pile
  of nested if/else branches.
- Change one logical point at a time. Before final output, close the loop:
  debug, first-principles review, simplify, then verify.
- Production code must not depend on mocks. Debug mocks must live behind a
  localhost-only `/mock` entry and stay git-excluded.

## Task Workspace

- Task process files belong under `doc/`: `task_plan.md`, `progress.md`,
  `findings.md`, `task_issue.md`, and `lessons.md`.
- Before code edits, read `doc/lessons.md`, mark the current task in
  `doc/task_issue.md`, and initialize or update `doc/task_plan.md`.
- Append `doc/progress.md` and `doc/findings.md` during execution, not only at
  the end. Do not carry a separate root-level process-doc directory.

## AGENTS Hierarchy

- Read AGENTS files in this order: global AGENTS.md, project-root AGENTS.md,
  then nested AGENTS.md files from root toward the target path.
- The nearest AGENTS.md wins when instructions conflict. The current user
  message wins over every AGENTS.md file.
- If a project has no root AGENTS.md, goal-context should generate a
  minimal one before dispatching subagents.
"""


PROJECT_TEMPLATE = f"""{GENERATED_MARKER}
# AGENTS.md

This project AGENTS.md was generated by goal-context because no
project-root AGENTS.md existed.

## Project Defaults

- Follow the global AGENTS.md first, then this file, then any nested AGENTS.md
  files closer to the edited path.
- Keep edits scoped to the user's requested goal and preserve unrelated local
  changes.
- Put task process docs under `doc/`, not in the repository root.

## Maintenance

- Replace this generated file with project-specific build, test, style,
  security, architecture, and ownership instructions as they become known.
- Refresh the managed `Path Index` block with `ensure_agents_context.py
  --include-path-index --update-project-path-index` after project structure,
  commands, workspace units, or nested AGENTS.md files change.
"""


DOC_TEMPLATES = {
    "task_plan.md": "# Task Plan\n\n",
    "progress.md": "# Progress\n\n",
    "findings.md": "# Findings\n\n",
    "task_issue.md": "# Task Issues\n\n",
    "lessons.md": "# Lessons\n\n",
}


def utc_now() -> str:
    return (
        datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")
    )


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def read_optional(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None


def write_if_missing(path: Path, text: str) -> bool:
    if path.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


def relpath(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root).as_posix()
    except ValueError:
        return str(path)


def add_unique(
    rows: list[dict[str, str]], path: str, reason: str, *, max_items: int
) -> None:
    if len(rows) >= max_items:
        return
    if any(row.get("path") == path for row in rows):
        return
    rows.append({"path": path, "reason": reason})


def path_depth(rel: str) -> int:
    if rel in {"", "."}:
        return 0
    return len(Path(rel).parts)


def describe_path(rel: str, name: str, *, is_dir: bool) -> str:
    lower = name.lower()
    if name == "AGENTS.md":
        return "agent instructions for this scope"
    if lower.startswith("readme"):
        return "project overview and setup notes"
    if name in MANIFEST_NAMES:
        return "project manifest or command/dependency entry"
    if rel.startswith("doc/") or rel == "doc":
        return "harness task workspace and durable task notes"
    if rel.startswith("docs/") or rel == "docs":
        return "project documentation"
    if rel.startswith(".agent-context/") or rel == ".agent-context":
        return "generated agent-context map and safety metadata"
    if lower in {"tests", "test"} or "/tests" in rel or "/test" in rel:
        return "test entry point"
    if is_dir:
        return "workspace directory"
    return "important project path"


def iter_repo_paths(repo_root: Path, max_depth: int) -> list[tuple[Path, str, bool]]:
    rows: list[tuple[Path, str, bool]] = []
    for dirpath, dirnames, filenames in os.walk(repo_root):
        current = Path(dirpath)
        rel_dir = relpath(current, repo_root)
        depth = path_depth(rel_dir)
        dirnames[:] = sorted(
            name
            for name in dirnames
            if name not in EXCLUDED_DIRS
            and path_depth(f"{rel_dir}/{name}" if rel_dir != "." else name) <= max_depth
        )
        if depth <= max_depth:
            rows.append((current, rel_dir, True))
        for filename in sorted(filenames):
            path = current / filename
            rel = relpath(path, repo_root)
            if path_depth(rel) <= max_depth:
                rows.append((path, rel, False))
    return rows


def build_path_index(
    repo_root: Path,
    *,
    target_paths: list[Path],
    doc_workspace: dict[str, Any],
    max_depth: int,
    max_items: int,
) -> dict[str, Any]:
    sections: dict[str, list[dict[str, str]]] = {
        "start_here": [],
        "agents_files": [],
        "workspace_units": [],
        "commands_and_manifests": [],
        "source_roots": [],
        "tests": [],
        "docs": [],
        "task_docs": [],
        "generated_context": [],
        "sensitive_paths": [],
    }
    for target in target_paths:
        add_unique(
            sections["start_here"],
            relpath(target, repo_root),
            "requested target path",
            max_items=max_items,
        )
    for name in [
        "AGENTS.md",
        "README.md",
        "README.zh-CN.md",
        "pyproject.toml",
        "Makefile",
        "package.json",
    ]:
        path = repo_root / name
        if path.exists():
            add_unique(
                sections["start_here"],
                name,
                describe_path(name, name, is_dir=path.is_dir()),
                max_items=max_items,
            )

    doc_required = (
        doc_workspace.get("required_files") if isinstance(doc_workspace, dict) else []
    )
    if isinstance(doc_required, list):
        for raw in doc_required:
            path = Path(str(raw))
            add_unique(
                sections["task_docs"],
                relpath(path, repo_root),
                "required task process doc",
                max_items=max_items,
            )

    for path, rel, is_dir in iter_repo_paths(repo_root, max_depth):
        name = path.name
        lower = name.lower()
        if name == "AGENTS.md":
            add_unique(
                sections["agents_files"],
                rel,
                describe_path(rel, name, is_dir=is_dir),
                max_items=max_items,
            )
        if not is_dir and name in MANIFEST_NAMES:
            add_unique(
                sections["commands_and_manifests"],
                rel,
                describe_path(rel, name, is_dir=False),
                max_items=max_items,
            )
            unit = relpath(path.parent, repo_root)
            add_unique(
                sections["workspace_units"],
                unit,
                f"workspace unit containing {name}",
                max_items=max_items,
            )
        if is_dir and (
            lower in {"docs", "doc"}
            or rel.startswith("docs/")
            or rel.startswith("doc/")
        ):
            add_unique(
                sections["docs"],
                rel,
                describe_path(rel, name, is_dir=True),
                max_items=max_items,
            )
        if not is_dir and (
            lower.startswith("readme")
            or rel.startswith("docs/")
            or rel.startswith("doc/")
        ):
            add_unique(
                sections["docs"],
                rel,
                describe_path(rel, name, is_dir=False),
                max_items=max_items,
            )
        if is_dir and (
            lower in {"tests", "test"}
            or rel.endswith("/tests")
            or rel.endswith("/test")
        ):
            add_unique(sections["tests"], rel, "test directory", max_items=max_items)
        if not is_dir and any(part in {"tests", "test"} for part in Path(rel).parts):
            add_unique(sections["tests"], rel, "test file", max_items=max_items)
        if is_dir and rel.startswith(".agent-context"):
            add_unique(
                sections["generated_context"],
                rel,
                describe_path(rel, name, is_dir=True),
                max_items=max_items,
            )
        if not is_dir and rel.startswith(".agent-context/"):
            add_unique(
                sections["generated_context"],
                rel,
                describe_path(rel, name, is_dir=False),
                max_items=max_items,
            )
        if not is_dir and path.suffix in CODE_SUFFIXES:
            add_unique(
                sections["source_roots"],
                relpath(path.parent, repo_root),
                "contains source/config files",
                max_items=max_items,
            )
        if (
            lower == ".env"
            or path.suffix in SENSITIVE_SUFFIXES
            or "secret" in lower
            or "token" in lower
            or lower.endswith(".key")
        ):
            add_unique(
                sections["sensitive_paths"],
                rel,
                "sensitive or environment-specific path; do not pack or edit casually",
                max_items=max_items,
            )

    return {
        "generated_at": utc_now(),
        "max_depth": max_depth,
        "max_items_per_section": max_items,
        "sections": {key: rows for key, rows in sections.items() if rows},
    }


def format_path_index_markdown(path_index: dict[str, Any]) -> str:
    titles = [
        ("start_here", "Start Here"),
        ("agents_files", "AGENTS Files"),
        ("workspace_units", "Workspace Units"),
        ("commands_and_manifests", "Commands And Manifests"),
        ("source_roots", "Source Roots"),
        ("tests", "Tests"),
        ("docs", "Docs"),
        ("task_docs", "Task Docs"),
        ("generated_context", "Generated Context"),
        ("sensitive_paths", "Sensitive Paths"),
    ]
    lines = [
        PATH_INDEX_BEGIN,
        "## Path Index",
        "",
        f"- Generated: {path_index.get('generated_at')}",
        f"- Max depth: {path_index.get('max_depth')}",
        f"- Max items per section: {path_index.get('max_items_per_section')}",
        "",
    ]
    sections = (
        path_index.get("sections")
        if isinstance(path_index.get("sections"), dict)
        else {}
    )
    for key, title in titles:
        rows = sections.get(key)
        if not isinstance(rows, list) or not rows:
            continue
        lines.extend([f"### {title}", ""])
        for row in rows:
            if not isinstance(row, dict):
                continue
            lines.append(f"- `{row.get('path')}` - {row.get('reason')}")
        lines.append("")
    lines.append(PATH_INDEX_END)
    return "\n".join(lines).rstrip() + "\n"


def update_managed_block(text: str, block: str) -> tuple[str, str]:
    for begin, end_marker, action in [
        (PATH_INDEX_BEGIN, PATH_INDEX_END, "updated"),
    ]:
        start = text.find(begin)
        end = text.find(end_marker)
        if start != -1 and end != -1 and end > start:
            end += len(end_marker)
            return text[:start].rstrip() + "\n\n" + block.rstrip() + "\n" + text[
                end:
            ].lstrip(), action
    for begin, end_marker in LEGACY_PATH_INDEX_MARKERS:
        start = text.find(begin)
        end = text.find(end_marker)
        if start != -1 and end != -1 and end > start:
            end += len(end_marker)
            return text[:start].rstrip() + "\n\n" + block.rstrip() + "\n" + text[
                end:
            ].lstrip(), "migrated_legacy"
    suffix = "" if text.endswith("\n") else "\n"
    return text.rstrip() + f"{suffix}\n{block}", "inserted"


def update_project_path_index(
    repo_root: Path, path_index: dict[str, Any]
) -> dict[str, Any]:
    agents_path = repo_root / "AGENTS.md"
    if not agents_path.exists():
        return {"action": "missing", "path": str(agents_path)}
    text = agents_path.read_text(encoding="utf-8")
    new_text, action = update_managed_block(
        text, format_path_index_markdown(path_index)
    )
    if new_text == text:
        return {"action": "unchanged", "path": str(agents_path)}
    agents_path.write_text(new_text, encoding="utf-8")
    return {"action": action, "path": str(agents_path)}


def summarize_agents(
    path: Path, scope: str, precedence: int, *, include_content: bool
) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8", errors="replace")
    row: dict[str, Any] = {
        "path": str(path),
        "scope": scope,
        "precedence": precedence,
        "line_count": len(text.splitlines()),
        "sha256": sha256_text(text),
    }
    if include_content:
        row["content"] = text
    return row


def resolve_repo_root(raw: Path) -> Path:
    return raw.expanduser().resolve()


def resolve_target(repo_root: Path, raw: str) -> tuple[Path | None, str | None]:
    path = Path(raw).expanduser()
    if not path.is_absolute():
        path = repo_root / path
    resolved = path.resolve()
    try:
        resolved.relative_to(repo_root)
    except ValueError:
        return None, f"target_path escapes repo_root: {raw}"
    return resolved, None


def target_directory(path: Path) -> Path:
    if path.exists() and path.is_file():
        return path.parent
    if path.suffix and not path.exists():
        return path.parent
    return path


def ancestor_dirs(repo_root: Path, target_dir: Path) -> list[Path]:
    dirs: list[Path] = []
    current = target_dir
    while True:
        dirs.append(current)
        if current == repo_root:
            break
        parent = current.parent
        if parent == current:
            break
        current = parent
    return list(reversed(dirs))


def ensure_agents_files(
    repo_root: Path,
    global_agents: Path,
    *,
    create_global: bool,
    create_project: bool,
    require_project: bool,
) -> tuple[dict[str, Any], dict[str, Any], list[str], list[str]]:
    warnings: list[str] = []
    blockers: list[str] = []

    global_created = False
    if not global_agents.exists() and create_global:
        global_created = write_if_missing(global_agents, GLOBAL_TEMPLATE)
    global_info = {
        "path": str(global_agents),
        "exists": global_agents.exists(),
        "action": "generated"
        if global_created
        else "read_existing"
        if global_agents.exists()
        else "missing",
    }
    if not global_agents.exists():
        warnings.append(f"global AGENTS.md missing: {global_agents}")

    project_agents = repo_root / "AGENTS.md"
    project_created = False
    if not project_agents.exists() and create_project:
        project_created = write_if_missing(project_agents, PROJECT_TEMPLATE)
    project_exists = project_agents.exists()
    project_info = {
        "path": str(project_agents),
        "exists": project_exists,
        "action": "generated"
        if project_created
        else "read_existing"
        if project_exists
        else "missing_not_generated",
    }
    if not project_exists:
        message = f"project AGENTS.md missing: {project_agents}"
        if require_project:
            blockers.append(message)
        else:
            warnings.append(message)
    return global_info, project_info, warnings, blockers


def build_agents_chain(
    repo_root: Path,
    global_agents: Path,
    target_path: Path,
    *,
    include_content: bool,
) -> list[dict[str, Any]]:
    chain: list[dict[str, Any]] = []
    precedence = 0
    if global_agents.exists():
        chain.append(
            summarize_agents(
                global_agents, "global", precedence, include_content=include_content
            )
        )
        precedence += 1
    target_dir = target_directory(target_path)
    for directory in ancestor_dirs(repo_root, target_dir):
        agents_path = directory / "AGENTS.md"
        if agents_path.exists():
            scope = "project" if directory == repo_root else "nested"
            chain.append(
                summarize_agents(
                    agents_path, scope, precedence, include_content=include_content
                )
            )
            precedence += 1
    return chain


def inspect_doc_workspace(
    repo_root: Path,
    *,
    init_doc_workspace: bool,
    record_boot: bool,
    task_id: str,
    task_summary: str,
) -> dict[str, Any]:
    doc_dir = repo_root / "doc"
    root_violations = [
        str(repo_root / name) for name in PROCESS_DOCS if (repo_root / name).exists()
    ]
    created: list[str] = []
    updated: list[str] = []
    missing: list[str] = []

    if init_doc_workspace:
        doc_dir.mkdir(parents=True, exist_ok=True)
        for name in PROCESS_DOCS:
            path = doc_dir / name
            if write_if_missing(path, DOC_TEMPLATES[name]):
                created.append(str(path))

    for name in PROCESS_DOCS:
        path = doc_dir / name
        if not path.exists():
            missing.append(str(path))

    if record_boot and not missing:
        marker = f"{BOOT_MARKER_PREFIX}{task_id} -->"
        now = utc_now()
        issue_path = doc_dir / "task_issue.md"
        issue_text = issue_path.read_text(encoding="utf-8")
        if marker not in issue_text:
            issue_path.write_text(
                f"{issue_text.rstrip()}\n\n{marker}\n- {now} [in_progress] {task_summary}\n",
                encoding="utf-8",
            )
            updated.append(str(issue_path))
        plan_path = doc_dir / "task_plan.md"
        plan_text = plan_path.read_text(encoding="utf-8")
        if marker not in plan_text:
            plan_path.write_text(
                f"{plan_text.rstrip()}\n\n{marker}\n## {task_id}\n\n- Status: in_progress\n- Goal: {task_summary}\n",
                encoding="utf-8",
            )
            updated.append(str(plan_path))

    blockers: list[str] = []
    warnings: list[str] = []
    if root_violations:
        blockers.append(
            "root process docs must move under doc/: " + ", ".join(root_violations)
        )
    if missing:
        warnings.append("doc workspace missing files: " + ", ".join(missing))

    status = "block" if blockers else "warn" if warnings else "ok"
    return {
        "path": str(doc_dir),
        "status": status,
        "required_files": [str(doc_dir / name) for name in PROCESS_DOCS],
        "missing": missing,
        "root_violations": root_violations,
        "created": created,
        "updated": updated,
        "warnings": warnings,
        "blockers": blockers,
    }


def resolve_agents_context(args: argparse.Namespace) -> dict[str, Any]:
    repo_root = resolve_repo_root(args.repo_root)
    global_agents = args.global_agents.expanduser().resolve()
    global_info, project_info, warnings, blockers = ensure_agents_files(
        repo_root,
        global_agents,
        create_global=bool(args.create_missing_global_agents),
        create_project=bool(args.create_missing_project_agents),
        require_project=bool(args.require_project_agents),
    )

    target_inputs = args.target_path or ["."]
    resolved_targets: list[Path] = []
    for raw_target in target_inputs:
        resolved, error = resolve_target(repo_root, raw_target)
        if error:
            blockers.append(error)
            continue
        assert resolved is not None
        resolved_targets.append(resolved)

    doc_workspace = inspect_doc_workspace(
        repo_root,
        init_doc_workspace=bool(args.init_doc_workspace),
        record_boot=bool(args.record_boot),
        task_id=str(args.task_id),
        task_summary=str(args.task_summary),
    )
    warnings.extend(doc_workspace.get("warnings") or [])
    blockers.extend(doc_workspace.get("blockers") or [])

    path_index: dict[str, Any] | None = None
    if args.include_path_index or args.update_project_path_index:
        path_index = build_path_index(
            repo_root,
            target_paths=resolved_targets or [repo_root],
            doc_workspace=doc_workspace,
            max_depth=max(0, int(args.path_index_max_depth)),
            max_items=max(1, int(args.path_index_max_items)),
        )
    if args.update_project_path_index and path_index is not None:
        path_index_action = update_project_path_index(repo_root, path_index)
        project_info["path_index_action"] = path_index_action.get("action")
        project_info["path_index_path"] = path_index_action.get("path")

    targets: list[dict[str, Any]] = []
    for resolved in resolved_targets:
        chain = build_agents_chain(
            repo_root,
            global_agents,
            resolved,
            include_content=bool(args.include_content),
        )
        targets.append(
            {
                "target_path": str(resolved),
                "agents_chain": chain,
                "nearest_agents": chain[-1]["path"] if chain else None,
                "nearest_scope": chain[-1]["scope"] if chain else None,
            }
        )

    payload: dict[str, Any] = {
        "schema": "goal-context.agents_context.v1",
        "generated_at": utc_now(),
        "repo_root": str(repo_root),
        "global_agents": global_info,
        "project_agents": project_info,
        "precedence": [
            "current_user_message",
            "nearest_nested_AGENTS.md",
            "project_root_AGENTS.md",
            "global_AGENTS.md",
        ],
        "read_order": [
            "global_AGENTS.md",
            "project_root_AGENTS.md",
            "nested_AGENTS.md from repo root toward target path",
        ],
        "targets": targets,
        "doc_workspace": doc_workspace,
        "warnings": warnings,
        "blockers": blockers,
        "stop_required": bool(blockers),
    }
    if path_index is not None:
        payload["path_index"] = path_index
    return payload


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Resolve AGENTS.md hierarchy for goal runs"
    )
    parser.add_argument("--repo-root", type=Path, required=True)
    parser.add_argument("--target-path", action="append", default=[])
    parser.add_argument("--global-agents", type=Path, default=DEFAULT_GLOBAL_AGENTS)
    parser.add_argument("--create-missing-global-agents", action="store_true")
    parser.add_argument("--create-missing-project-agents", action="store_true")
    parser.add_argument("--require-project-agents", action="store_true")
    parser.add_argument("--init-doc-workspace", action="store_true")
    parser.add_argument("--record-boot", action="store_true")
    parser.add_argument("--task-id", default="goal-task")
    parser.add_argument("--task-summary", default="goal AGENTS.md context task")
    parser.add_argument("--include-content", action="store_true")
    parser.add_argument("--include-path-index", action="store_true")
    parser.add_argument("--update-project-path-index", action="store_true")
    parser.add_argument("--path-index-max-depth", type=int, default=4)
    parser.add_argument("--path-index-max-items", type=int, default=40)
    parser.add_argument(
        "--output", type=Path, help="Write the resolved context JSON to this path"
    )
    parser.add_argument("--json", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    payload = resolve_agents_context(args)
    json_text = json.dumps(payload, ensure_ascii=False, sort_keys=True, indent=2)
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json_text + "\n", encoding="utf-8")
    if args.json:
        print(json_text)
    else:
        print(f"repo_root: {payload['repo_root']}")
        print(f"project_agents: {payload['project_agents']['action']}")
        print(f"targets: {len(payload['targets'])}")
        print(f"doc_workspace: {payload['doc_workspace']['status']}")
        if payload["stop_required"]:
            print("stop_required: true")
    return 1 if payload["stop_required"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
